### ISSUE TITLE
Instance, but no bindings for tenant

### ISSUE THREAD

**Issue by gregorwolf** [SAP-samples/cloud-cap-multitenancy#2]
Hi @andrewlunde,

I've followed your instructions in the blogpost but unfortunately as soon as I hit the subscribe button in my consumer subaccount I see the following error messages when running `cf logs capmt-srv`:

> 2020-10-04T17:03:27.75+0200 [APP/PROC/WEB/0] ERR Instance, but no bindings for tenant TENANT-2141b92b-edff-4f81-a778-1f923c369643-META
>    2020-10-04T17:03:27.75+0200 [APP/PROC/WEB/0] ERR Error: Instance, but no bindings for tenant TENANT-2141b92b-edff-4f81-a778-1f923c369643-META
>    2020-10-04T17:03:27.75+0200 [APP/PROC/WEB/0] ERR     at /home/vcap/deps/0/node_modules/@sap/instance-manager/lib/service-manager/Backend.js:162:10
>    2020-10-04T17:03:27.75+0200 [APP/PROC/WEB/0] ERR     at /home/vcap/deps/0/node_modules/@sap/instance-manager/lib/service-manager/Client.js:92:5
>    2020-10-04T17:03:27.75+0200 [APP/PROC/WEB/0] ERR     at /home/vcap/deps/0/node_modules/@sap/instance-manager/lib/service-manager/Resource.js:147:14
>    2020-10-04T17:03:27.75+0200 [APP/PROC/WEB/0] ERR     at /home/vcap/deps/0/node_modules/@sap/instance-manager/lib/service-manager/Resource.js:130:5
>    2020-10-04T17:03:27.75+0200 [APP/PROC/WEB/0] ERR     at Request._callback (/home/vcap/deps/0/node_modules/@sap/instance-manager/lib/service-manager/Resource.js:172:7)
>    2020-10-04T17:03:27.75+0200 [APP/PROC/WEB/0] ERR     at Request.self.callback (/home/vcap/deps/0/node_modules/request/request.js:185:22)
>    2020-10-04T17:03:27.75+0200 [APP/PROC/WEB/0] ERR     at Request.emit (events.js:198:13)
>    2020-10-04T17:03:27.75+0200 [APP/PROC/WEB/0] ERR     at Request.<anonymous> (/home/vcap/deps/0/node_modules/request/request.js:1154:10)
>    2020-10-04T17:03:27.75+0200 [APP/PROC/WEB/0] ERR     at Request.emit (events.js:198:13)
>    2020-10-04T17:03:27.75+0200 [APP/PROC/WEB/0] ERR     at IncomingMessage.<anonymous> (/home/vcap/deps/0/node_modules/request/request.js:1076:12)

Hope you have a tip for me.

CU
Gregor

**Comment by andrewlunde** [comment]
Hey Gregor,

Thanks for taking you time to kick around the code sample.

I appreciate the hint about hiding the passwords.  Will have to use that trick in the future as it’s always bothered me to leave things in the open in any way.

As far as this issue, from the logs, it seems the HDI container didn’t get created properly or was created in a way that left it in a weird state.

I use a collection of Postman calls that I can run outside of the app to verify the state of things (and clean them up if things go wrong).

Attaching them here.   You’ll have to change the environment settings to match yours.

Maybe if you’re still having issues, we can get on a call and troubleshoot.  I’m tied up this week, but am available next week.

What’s your immediacy?

-Andrew
+1 404-416-5688 Cell

**Comment by gregorwolf** [comment]
Hi @andrewlunde,

unfortunately your Postman collection didn't made it through. Maybe you can add them to the repository. In my pull request you will see the [REST Client](https://marketplace.visualstudio.com/items?itemName=humao.rest-client) files that I've adde. I like this even more than Postman. You can read variables from a .env file, process the result into variables and that is plain text files.

Best regards
Gregor

**Comment by andrewlunde** [comment]
I've merged your PR so will

**Comment by andrewlunde** [comment]
close this issue now.   Create a new one if the result is not meeting your needs.
